services:
    nginx:
        image: nginx:1.30.3-alpine
        ports:
            - "80:80"
        networks:
            - edge
            - backend
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d/:ro
    podinfo:
        image: ghcr.io/stefanprodan/podinfo:6.14.0
        networks:
            - backend
    # agent reconciliation test
networks:
    backend:
    edge:
