services:
    homelab-api:
        image: ghcr.io/viper6z/homelab-api:v1
        networks:
            - backend
    nginx:
        image: nginx:1.30.3-alpine
        ports:
            - "80:80"
        networks:
            - edge
            - backend
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d/:ro
networks:
    backend:
    edge:
