services:
  homelab-api:
    build: .
    container_name: homelab-api
    restart: unless-stopped
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homelab-api.rule=Host(`api.lab.home`)"
      - "traefik.http.routers.homelab-api.entrypoints=web"
      - "traefik.http.services.homelab-api.loadbalancer.server.port=5000"
