location = / {
  proxy_pass http://podinfo:9898;
}

location = /healthz {
  proxy_pass http://podinfo:9898;
}

location = /readyz {
  proxy_pass http://podinfo:9898;
}

location = /version {
  proxy_pass http://podinfo:9898;
}

