name: cd 
on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: checkout repo
        uses: actions/checkout@v7

      - name: oidc login
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::127372371185:role/homelab_cd_terraform
          aws-region: eu-north-1

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: terraform fmt
        run: terraform fmt -check

      - name: terraform init
        run: terraform init

      - name: terraform validate
        run: terraform validate

      - name: terraform plan
        run: terraform plan

  deploy:
    if: github.event.pull_request.merged == true
    needs: plan
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: OIDC login
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::127372371185:role/homelab_cd_terraform
          aws-region: eu-north-1

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        run: terraform apply -auto-approve

      - name: send deploy command through SSM 
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Role,Values=seal-host" \
            --parameters 'commands=["pwd","docker --version"]'

