name: cd 
on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: checkout repo
        uses: actions/checkout@v7

      - name: oidc login
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::127372371185:role/homelab_cd_terraform
          aws-region: eu-north-1

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: terraform fmt
        run: terraform fmt -check

      - name: terraform init
        run: terraform init

      - name: terraform validate
        run: terraform validate

      - name: terraform plan
        run: terraform plan

  deploy:
    if: github.event.pull_request.merged == true
    needs: plan
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: OIDC login
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::127372371185:role/homelab_cd_terraform
          aws-region: eu-north-1

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        run: terraform apply -auto-approve

      - name: send deploy command through SSM 
        run: |

          INSTANCE_ID=$( #save the instance id 
            aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].InstanceId' \
              --filters \
                "Name=tag:Role,Values=seal-host" \
                "Name=instance-state-name,Values=running" \
              --output text
            )
          
          COMMAND_ID=$( #save the command id
            aws ssm send-command \
              --document-name "AWS-RunShellScript" \
              --instance-ids "$INSTANCE_ID" \
              --parameters '{
                  "commands": [
                    "set -e",
                    "if [ -d /opt/seal/.git ]; then",
                    "  cd /opt/seal",
                    "  git pull --ff-only",
                    "else",
                    "  git clone https://github.com/viper6z/homelab.git /opt/seal",
                    "fi",
                    "cd /opt/seal",
                    "docker compose up -d --build --remove-orphans",
                    "docker compose exec -T nginx nginx -s reload" 
                  ]
                }' \
              --query 'Command.CommandId' \
              --output text
            )

          echo "Target instance: $INSTANCE_ID"
          echo "SSM command: $COMMAND_ID"

          set +e 
          #for now, dont exit if we get error 
          #wait until command is executed 
          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id "$INSTANCE_ID"
          #if it fails save it here 
          WAIT_EXIT_CODE=$? 

          set -e #now we can exit on error 
          #so even if the comamnd isnt executed because of error, we are still able to query it for info, otherwise it would just fail
          aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id "$INSTANCE_ID" \
            --query '{Status:Status,ExitCode:ResponseCode,Stdout:StandardOutputContent,Stderr:StandardErrorContent}' \
            --output json

          exit "$WAIT_EXIT_CODE" #then we exit if command didnt execute

