name: continuous integration
on:
  pull_request:
    branches:
      - main 


jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: checkout repo
        uses: actions/checkout@v7
      
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: terraform fmt
        run: terraform fmt -check

      - name: terraform init
        run: terraform init -backend=false

      - name: terraform validate
        run: terraform validate

  ansible:
    runs-on: ubuntu-latest

    defaults:
      run: 
        working-directory: ansible

    steps:
      - name: checkout repo
        uses: actions/checkout@v7

      - name: install ansible
        run: python3 -m pip install ansible-core

      - name: install requirements galaxy
        run: ansible-galaxy collection install -r requirements.yml 

      - name: ansible syntax check
        run: ansible-playbook -i inventory.ini playbook.yaml --syntax-check

  compose:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v7

      - name: validate compose
        run: docker compose config

