name: continuous integration
on:
  pull_request:
    branches:
      - main 


jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: checkout repo
        uses: actions/checkout@v7
      
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: terraform fmt
        run: terraform fmt -check

      - name: terraform init
        run: terraform init -backend=false

      - name: terraform validate
        run: terraform validate


  #OBS: ansible validation was here before but removed now for cloud init WIP

  compose:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v7

      - name: validate compose
        run: docker compose config

  nginx:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v7

      - name: docker compose up 
        run: docker compose up --wait

      - name: test nginx
        run: docker compose exec -T nginx nginx -t

      - name: docker compose down
        run: docker compose down
        if: ${{ always() }}

  go:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: interface

    steps:
      - name: checkout repo
        uses: actions/checkout@v7

      - name: setup go
        uses: actions/setup-go@v7
        with:
          go-version-file: interface/go.mod
          cache-dependency-path: interface/go.sum

      - name: check formatting
        run: test -z "$(gofmt -l .)"

      - name: vet
        run: go vet ./...

      - name: test
        run: go test ./...

      - name: build
        run: go build ./...
